language: node_js
os: linux
node_js:
  - lts/*
install:
  - yarn install
jobs:
  include:
    # 测试代码格式
    - stage: linter-test
      name: "Use eslint to test your code"
      script:
        - yarn run lint:checl

stages:
  - name: linter-test
