language: node_js
os: linux
node_js:
  - lts/*
install:
  - yarn install
jobs:
  include:
    # 测试代码格式
    - stage: linter-test
      name: "Use eslint to test your code"
      script:
        - yarn run lint:check

    # 测试 TS 构建
    - stage: ts-test
      name: "Run tsc to test TS compile"
      script:
        - yarn run tsc

stages:
  - name: linter-test
  - name: ts-test
